/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardPopup: typeof import('./src/components/CardPopup.vue')['default']
    CardsList: typeof import('./src/components/CardsList.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    New: typeof import('./src/components/New.vue')['default']
    Order: typeof import('./src/components/Order.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./src/components/Signin.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
  }
}
